apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cipherwatch-backend
  namespace: monitoring
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: aura-backend

  namespaceSelector:
    matchNames:
      - cipherwatch

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
