apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cipherwatch
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Lite-os15/cipherwatch-gitops.git
    targetRevision: main
    path: apps/cipherwatch

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
